[package]
edition = "2024"

name = "credence-lib"
description = "An unfussy web server designed for straightforward authoring and scalable performance"
version = "0.0.3"
rust-version = "1.89"

license = "MIT OR Apache-2.0"
repository = "https://github.com/tliron/rust-credence"
documentation = "https://docs.rs/credence-lib"
authors = ["Tal Liron"]

readme = "../../README.md"

categories = [
    "web-programming",
    "web-programming::http-server",
] # https://crates.io/category_slugs
keywords = ["web", "axum", "tower"]

[dependencies]
axum = "0.8.4"
axum-server = { version = "0.7.2", features = ["tls-rustls"] }
chrono = "0.4.41"
compris = { version = "=0.0.7", default-features = false, features = ["derive", "serde", "yaml", "json"] }
dateparser = "0.2.1"
duration-str = "0.17.0"
dynosaur = "0.3.0"
http = "1.3.1"
httpdate = "1.0.3"
hyper = "1.6.0"
kutil-cli = { version = "=0.0.9", features = ["derive"] }
kutil-http = { version = "=0.0.6", features = [
    "acme",
    "axum",
    "file",
    "moka",
    "tls",
] }
kutil-io = "=0.0.5"
kutil-std = { version = "=0.0.6", features = ["derive", "zerocopy"] }
markdown = "1.0.0"
minijinja = { version = "2.11.0", features = ["loader", "unicode", "json", "urlencode", "loop_controls", "speedups"] }
minijinja-contrib = { version = "2.11.0", features = [
    "datetime",
    "rand",
    "time",
    "timezone",
    "unicode_categories",
    "unicode_wordwrap",
    "wordcount",
    "wordwrap",
] }
moka = { version = "0.12.10", features = ["future"] }
notify = "8.2.0"
regex = "1.11.1"
serde = "1.0.219"
thiserror = "2.0.12"
tracing = "0.1.41"
tokio = { version = "1.47.1", features = ["rt-multi-thread", "signal"] }
tokio-util = "0.7.16"
tower-http = { version = "0.6.6", features = [
    "fs",
    "limit",
    "timeout",
    "trace",
] }

# https://stackoverflow.com/a/61417700
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
